VanillaVeterans_loot_table = {
{["loot_id"] = "19341",["loot_name"] = "Lifegiving Gem",["prio"] = "Prio: Tanks",},
{["loot_id"] = "19351",["loot_name"] = "Maladath Runed Blade of the Black Flight",["prio"] = "Prio: CoreRaider + Rogue = Warrior DPS = Warrior Tank",},
{["loot_id"] = "19361",["loot_name"] = "Ashjre'thul Crossbow of Smiting",["prio"] = "Prio: Hunter",},
{["loot_id"] = "19387",["loot_name"] = "Chromatic Boots",["prio"] = "Prio: Warrior DPS = Warrior Tanks = Ret Paladin",},
{["loot_id"] = "19349",["loot_name"] = "Elementium Reinforced Bulwark",["prio"] = "Prio: Warrior tank",},
{["loot_id"] = "19390",["loot_name"] = "Taut Dragonhide Gloves",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19389",["loot_name"] = "Taut Dragonhide Shoulderpads",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19405",["loot_name"] = "Malfurion s Blessed Bulwark",["prio"] = "Prio: Druid Feral > MS->OS",},
{["loot_id"] = "19398",["loot_name"] = "Cloak of Firemaw",["prio"] = "Prio: Hunter = Rogue = Warrior DPS = Ret Paladin",},
{["loot_id"] = "19432",["loot_name"] = "Circle of Applied Force",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19431",["loot_name"] = "Styleen's Impeding Scarab",["prio"] = "Prio: Warrior Tank",},
{["loot_id"] = "19364",["loot_name"] = "Ashkandi Greatsword of the Brotherhood",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19363",["loot_name"] = "Crul'shorukh Edge of Chaos",["prio"] = "Prio: Warrior DPS",},
{["loot_id"] = "19360",["loot_name"] = "Lok'amir il Romathis",["prio"] = "Prio: CoreRadier + Shadow Priest = Paladin = Druid Resto",},
{["loot_id"] = "19375",["loot_name"] = "Mish'undare Circlet of the Mind Flayer",["prio"] = "Prio: CoreRaider + Mage = Warlock = Paladin > MS->OS",},
{["loot_id"] = "18564",["loot_name"] = "Bindings of the Windseeker",["prio"] = "Prio: Eatthat > LootConcil",},
{["loot_id"] = "18832",["loot_name"] = "Brutality Blade",["prio"] = "Prio: Rogue = Warrior DPS = Warrior Tank = Hunter",},
{["loot_id"] = "18805",["loot_name"] = "Core Hound Tooth",["prio"] = "Prio: Dagger Rogue = Warrior DPS > Hunter > MS->OS",},
{["loot_id"] = "17063",["loot_name"] = "Band of Accuria",["prio"] = "Prio: Warrior Tank > Rogue = Hunter = Druid feral > MS->OS",},
{["loot_id"] = "18814",["loot_name"] = "Choker of the Fire Lord",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17102",["loot_name"] = "Cloak of the Shrouded Mists",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19137",["loot_name"] = "Onslaught Girdle",["prio"] = "Prio: Warrior DPS > Warrior Tank > Ret Paladin > MS->OS",},
{["loot_id"] = "19143",["loot_name"] = "Flameguard Gauntlets",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18816",["loot_name"] = "Perdition's Blade",["prio"] = "Prio: Dagger Rogue > MS->OS",},
{["loot_id"] = "19435",["loot_name"] = "Essence Gatherer",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17077",["loot_name"] = "Crimson Shocker",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18861",["loot_name"] = "Flamewaker Legplates",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18879",["loot_name"] = "Heavy Dark Iron Ring",["prio"] = "Prio: Druid Feral > Warrior Tank > MS->OS",},
{["loot_id"] = "18870",["loot_name"] = "Helm of the Lifegiver",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18872",["loot_name"] = "Manastorm Leggings",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19147",["loot_name"] = "Ring of Spell Power",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19145",["loot_name"] = "Robe of Volatile Power",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18875",["loot_name"] = "Salamander Scale Pants",["prio"] = "Prio: Paladin > Druid Resto > MS->OS",},
{["loot_id"] = "18878",["loot_name"] = "Sorcerous Dagger",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19146",["loot_name"] = "Wristguards of Stability",["prio"] = "Prio: Warrior DPS = Ret Paladin > MS->OS",},
{["loot_id"] = "18823",["loot_name"] = "Aged Core Leather Gloves",["prio"] = "Prio: Rogue Dagger > MS->OS",},
{["loot_id"] = "19142",["loot_name"] = "Fire Runed Grimoire",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18824",["loot_name"] = "Magma Tempered Boots",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19136",["loot_name"] = "Mana Igniting Cord",["prio"] = "Prio: Mage = Shadow Priest = Warlock > Healers > MS->OS",},
{["loot_id"] = "18822",["loot_name"] = "Obsidian Edged Blade",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18821",["loot_name"] = "Quick Strike Ring",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19144",["loot_name"] = "Sabatons of the Flamewalker",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18820",["loot_name"] = "Talisman of Ephemeral Power",["prio"] = "Prio: Mage = Shadow Priest = Warlock > Healers > MS->OS",},
{["loot_id"] = "17109",["loot_name"] = "Choker of Enlightenment",["prio"] = "Prio: Mage = Warlock = Shadow Priest",},
{["loot_id"] = "17073",["loot_name"] = "Earthshaker",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18203",["loot_name"] = "Eskhandar's Right Claw",["prio"] = "Prio: Warrior Tank > MS->OS",},
{["loot_id"] = "17065",["loot_name"] = "Medallion of Steadfast Might",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17069",["loot_name"] = "Striker's Mark",["prio"] = "Prio: Rogue = Warrior DPS > Warrior Tank > Hunter > MS->OS",},
{["loot_id"] = "17105",["loot_name"] = "Aurastone Hammer",["prio"] = "Prio: Druid Resto = Paladin > Priest",},
{["loot_id"] = "17066",["loot_name"] = "Drillborer Disk",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17071",["loot_name"] = "Gutgore Ripper",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17110",["loot_name"] = "Seal of the Archmagus",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17074",["loot_name"] = "Shadowstrike",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17103",["loot_name"] = "Azuresong Mageblade",["prio"] = "Prio: Mage = Warlock = Paladin = Shadow Priest > MS->OS",},
{["loot_id"] = "17072",["loot_name"] = "Blastershot Launcher",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18842",["loot_name"] = "Staff of Dominance",["prio"] = "Prio: Mage = Warlock > Druid Resto > MS->OS",},
{["loot_id"] = "19140",["loot_name"] = "Cauterizing Band",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18806",["loot_name"] = "Core Forged Greaves",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18803",["loot_name"] = "Finkle's Lava Dredger",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19139",["loot_name"] = "Fireguard Shoulders",["prio"] = "Prio: Druid Feral = Warrior Tank > MS->OS",},
{["loot_id"] = "18811",["loot_name"] = "Fireproof Cloak",["prio"] = "Prio: Druid Feral = Warrior Tank > MS->OS",},
{["loot_id"] = "18808",["loot_name"] = "Gloves of the Hypnotic Flame",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18809",["loot_name"] = "Sash of Whispered Secrets",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18810",["loot_name"] = "Wild Growth Spaulders",["prio"] = "Prio: Druid Resto = Paladin",},
{["loot_id"] = "19138",["loot_name"] = "Band of Sulfuras",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17076",["loot_name"] = "Bonereaver's Edge",["prio"] = "Prio: Warrior DPS > Ret Paladin > MS->OS",},
{["loot_id"] = "18817",["loot_name"] = "Crown of Destruction",["prio"] = "Prio: Warrior DPS = Ret Paladin > Hunter > MS->OS",},
{["loot_id"] = "17107",["loot_name"] = "Dragon's Blood Cape",["prio"] = "Prio: Druid Feral > Warrior Tank > MS->OS",},
{["loot_id"] = "18815",["loot_name"] = "Essence of the Pure Flame",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17106",["loot_name"] = "Malistar's Defender",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17082",["loot_name"] = "Shard of the Flame",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17104",["loot_name"] = "Spinal Reaper",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17067",["loot_name"] = "Ancient Cornerstone Grimoire",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18205",["loot_name"] = "Eskhandar's Collar",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17068",["loot_name"] = "Deathbringer",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "18423",["loot_name"] = "Head of Onyxia",["prio"] = "Prio: Warrior Tank = Druid Feral > Warrior DPS = Ret Paladin > Hunter = Rogue",},
{["loot_id"] = "17078",["loot_name"] = "Sapphiron Drape",["prio"] = "Prio: Mage = Warlock = Shadow Priest",},
{["loot_id"] = "17064",["loot_name"] = "Shard of the Scale",["prio"] = "Prio: Paladin = Priest = Druid Resto > MS->OS",},
{["loot_id"] = "18813",["loot_name"] = "Ring of Binding",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "17075",["loot_name"] = "Vis'kag the Bloodletter",["prio"] = "Prio: Rogue = Warrior DPS",},
{["loot_id"] = "19434",["loot_name"] = "Band of Dark Dominion",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19437",["loot_name"] = "Boots of Pure Thought",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19436",["loot_name"] = "Cloak of Draconic Might",["prio"] = "Prio: Warrior DPS = Warrior Tank = Ret Paladin > Rogue",},
{["loot_id"] = "19362",["loot_name"] = "Doom's Edge",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19354",["loot_name"] = "Draconic Avenger",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19358",["loot_name"] = "Draconic Maul",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19439",["loot_name"] = "Interlaced Shadow Jerkin",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19438",["loot_name"] = "Ringo's Blizzard Boots",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19369",["loot_name"] = "Gloves of Rapid Evolution",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19370",["loot_name"] = "Mantle of the Blackwing Cabal",["prio"] = "Prio: Mage = Shadow Priest = Warlock",},
{["loot_id"] = "19335",["loot_name"] = "Spineshatter",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19334",["loot_name"] = "The Untamed Blade",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19346",["loot_name"] = "Dragonfang Blade",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19372",["loot_name"] = "Helm of Endless Rage",["prio"] = "Prio: Warrior Tank > MS->OS",},
{["loot_id"] = "19371",["loot_name"] = "Pendant of the Fallen Dragon",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19348",["loot_name"] = "Red Dragonscale Protector",["prio"] = "Prio: Paladin > MS->OS",},
{["loot_id"] = "19373",["loot_name"] = "Black Brood Pauldrons",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19374",["loot_name"] = "Bracers of Arcane Accuracy",["prio"] = "Prio: Warlock = Shadow Priest = Mage",},
{["loot_id"] = "19350",["loot_name"] = "Heartstriker",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19399",["loot_name"] = "Black Ash Robe",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19365",["loot_name"] = "Claw of the Black Drake",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19400",["loot_name"] = "Firemaw's Clutch",["prio"] = "Prio: Shadow Priest > Mage = Warlock",},
{["loot_id"] = "19402",["loot_name"] = "Legguards of the Fallen Crusader",["prio"] = "Prio: Ret Paladin	= Warrior DPS = Warrior Tank > MS->OS",},
{["loot_id"] = "19403",["loot_name"] = "Band of Forced Concentration",["prio"] = "Prio: Warlock = Shadow Priest = Mage",},
{["loot_id"] = "19368",["loot_name"] = "Dragonbreath Hand Cannon",["prio"] = "Prio: Warrior Tank > MS->OS",},
{["loot_id"] = "19407",["loot_name"] = "Ebony Flame Gloves",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19406",["loot_name"] = "Drake Fang Talisman",["prio"] = "Prio: CoreRaider + Warrior Tank = Rogue = Warrior DPS",},
{["loot_id"] = "19433",["loot_name"] = "Emberweave Leggings",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19430",["loot_name"] = "Shroud of Pure Thought",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19357",["loot_name"] = "Herald of Woe ",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19367",["loot_name"] = "Dragon's Touch",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19353",["loot_name"] = "Drake Talon Cleaver",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19394",["loot_name"] = "Drake Talon Pauldrons",["prio"] = "Prio: CoreRaider + Warrior DPS = Warrior Tank = Ret Paladin",},
{["loot_id"] = "19397",["loot_name"] = "Ring of Blackrock",["prio"] = "Prio: Shadow Priest > Mage = Warlock",},
{["loot_id"] = "19355",["loot_name"] = "Shadow Wing Focus Staff",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19396",["loot_name"] = "Taut Dragonhide Belt",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19395",["loot_name"] = "Rejuvenating Gem",["prio"] = "Prio: CoreRaider + Priest = Paladin = Druid Resto",},
{["loot_id"] = "19388",["loot_name"] = "Angelista's Grasp",["prio"] = "Prio: Warlock > Priest Disc > Shadow Priest",},
{["loot_id"] = "19347",["loot_name"] = "Claw of Chromaggus",["prio"] = "Prio: Druid Resto = Warlock = Shadow Priest = Mage",},
{["loot_id"] = "19386",["loot_name"] = "Elementium Threaded Cloak",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19385",["loot_name"] = "Empowered Leggings",["prio"] = "Prio: Paladin = Priest = Druid Resto ",},
{["loot_id"] = "19392",["loot_name"] = "Girdle of the Fallen Crusader ",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19391",["loot_name"] = "Shimmering Geta",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19352",["loot_name"] = "Chromatically Tempered Sword",["prio"] = "Prio: Rogue = Warrior DPS",},
{["loot_id"] = "19376",["loot_name"] = "Archimtiros' Ring of Reckoning",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19381",["loot_name"] = "Boots of the Shadow Flame",["prio"] = "Prio: Rogue = Druid Feral > MS->OS",},
{["loot_id"] = "19378",["loot_name"] = "Cloak of the Brood Lord",["prio"] = "Prio: Shadow Priest = Mage = Warlock",},
{["loot_id"] = "19003",["loot_name"] = "Head of Nefarian",["prio"] = "Prio: Warrior Tank = Warrior DPS  = Rogue = Hunter = Ret Paladin",},
{["loot_id"] = "19377",["loot_name"] = "Prestor's Talisman of Connivery",["prio"] = "Prio: Rogue = Hunter > MS->OS",},
{["loot_id"] = "19382",["loot_name"] = "Pure Elementium Band",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19380",["loot_name"] = "Therazane's Link",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19379",["loot_name"] = "Neltharion's Tear",["prio"] = "Prio: Warlock = Mage = Shadow Priest",},
{["loot_id"] = "19356",["loot_name"] = "Staff of the Shadow Flame",["prio"] = "Prio: CoreRaider + Mage = Warlock > MS->OS",},
{["loot_id"] = "22711",["loot_name"] = "Cloak of the Hakkari Worshipers",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "22712",["loot_name"] = "Might of the Tribe",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "22713",["loot_name"] = "Zulian Sceptar of Rites",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "22714",["loot_name"] = "Sacrificial Gauntlets",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "22715",["loot_name"] = "Gloves of the Tormented",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "22716",["loot_name"] = "Belt of Untapped Power",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "22718",["loot_name"] = "Blooddrenched Mask",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "22720",["loot_name"] = "Zulian Headdress",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "22721",["loot_name"] = "Band of Servitude",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "22637",["loot_name"] = "Primal Hakkari Idol",["prio"] = "Max 1 per person per raid",},
{["loot_id"] = "22722",["loot_name"] = "Seal of the Gurubashi Berserker",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19915",["loot_name"] = "Zulian Defender",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19918",["loot_name"] = "Jeklik's Crusher",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19920",["loot_name"] = "Primalist's Band",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19923",["loot_name"] = "Jeklik's Opaline Talisman",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19928",["loot_name"] = "Animist's Spaulders",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "20265",["loot_name"] = "Peacekeeper Boots",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19900",["loot_name"] = "Zulian Stone Axe",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19903",["loot_name"] = "Fang of Venoxis",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19904",["loot_name"] = "Runed Bloodstained Hauberk",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19905",["loot_name"] = "Zanzil's Band",["prio"] = "Prio: Warlock > MS->OS",},
{["loot_id"] = "19906",["loot_name"] = "Blooddrenched Footpads",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19907",["loot_name"] = "Zulian Tigerhide Cloak",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19871",["loot_name"] = "Talisman of Protection",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19919",["loot_name"] = "Bloodstained Greaves",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19925",["loot_name"] = "Band of Jin",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19927",["loot_name"] = "Mar'li's Touch",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19930",["loot_name"] = "Mar'li's Eye",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "20032",["loot_name"] = "Flowing Ritual Robes",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19866",["loot_name"] = "Warblade of the Hakkari (Offhand)",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19867",["loot_name"] = "Bloodlord's Defender",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19869",["loot_name"] = "Blooddrenched Grips",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19870",["loot_name"] = "Hakkari Loa Cloak",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19873",["loot_name"] = "Overlord's Crimson Band",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19874",["loot_name"] = "Halberd of Smiting",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19877",["loot_name"] = "Animist's Leggings",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19878",["loot_name"] = "Bloodsoaked Pauldrons",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19893",["loot_name"] = "Zanzil's Seal",["prio"] = "Prio: Warlock > MS->OS",},
{["loot_id"] = "19895",["loot_name"] = "Bloodtinged Kilt",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "20038",["loot_name"] = "Mandokir's Sting",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19872",["loot_name"] = "Swift Razzashi Raptor",["prio"] = "Can only get one of the 2 mounts.",},
{["loot_id"] = "19896",["loot_name"] = "Thekal's Grasp",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19897",["loot_name"] = "Betrayer's Boots",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19898",["loot_name"] = "Seal of Jin",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19899",["loot_name"] = "Ritualistic Legguards",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19901",["loot_name"] = "Zulian Slicer",["prio"] = "Prio: Skinners > MS->OS",},
{["loot_id"] = "20266",["loot_name"] = "Peacekeeper Leggings",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19902",["loot_name"] = "Swift Zulian Tiger",["prio"] = "Can only get one of the 2 mounts.",},
{["loot_id"] = "19909",["loot_name"] = "Will of Arlok",["prio"] = "Prio: Druid Resto = Priest > Mage",},
{["loot_id"] = "19910",["loot_name"] = "Arlokk's Grasp",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19912",["loot_name"] = "Overlord's Onyx Band",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19922",["loot_name"] = "Arlokk's Hoodoo Stick",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19914",["loot_name"] = "Panther Hide Sack",["prio"] = "RAID ROLL",},
{["loot_id"] = "19885",["loot_name"] = "Jindo's Eye of Evil",["prio"] = "Prio: Paladin = Druid Resto = Priest > MS->OS",},
{["loot_id"] = "19886",["loot_name"] = "The Hexxer's Cover",["prio"] = "Prio: Shadow Priest > MS->OS",},
{["loot_id"] = "19887",["loot_name"] = "Bloodstained Legplates",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19888",["loot_name"] = "Overlord's Embrace",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19889",["loot_name"] = "Blooddrenched Leggings",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19890",["loot_name"] = "Jindo's Hexxer",["prio"] = "Prio: Paladin = Druid Resto > MS->OS",},
{["loot_id"] = "19891",["loot_name"] = "Jin'do's Bag of Whammies",["prio"] = "Prio: Warlock > MS->OS",},
{["loot_id"] = "19892",["loot_name"] = "Animist's Boots",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19894",["loot_name"] = "Bloodsoaked Gauntlet's",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19884",["loot_name"] = "Jindo's Judgement",["prio"] = "Prio: Warlock > MS->OS",},
{["loot_id"] = "19929",["loot_name"] = "Bloodtinged Gloves",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19802",["loot_name"] = "Heart of Hakkar",["prio"] = "Prio: Mage = Warlock = Shadow Priest > MS->OS",},
{["loot_id"] = "19852",["loot_name"] = "Ancient Hakkari Manslayer",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19853",["loot_name"] = "Gurubashi Destroyer",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19854",["loot_name"] = "Zin'rokh, Destroyer of Worlds",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19855",["loot_name"] = "Bloodsoaked Legplates",["prio"] = "Prio: Warrior Tank > MS->OS",},
{["loot_id"] = "19856",["loot_name"] = "The Eye of Hakkar",["prio"] = "Prio: Warrior DPS = Warrior Tank > MS->OS",},
{["loot_id"] = "19857",["loot_name"] = "Cloak of Consumption",["prio"] = "Prio: Warlock > MS->OS",},
{["loot_id"] = "19859",["loot_name"] = "Fang of the Faceless",["prio"] = "Prio: Hunter > MS->OS",},
{["loot_id"] = "19861",["loot_name"] = "Touch of Chaos",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19862",["loot_name"] = "Aegis of the Blood God",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19864",["loot_name"] = "Bloodcaller",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "19865",["loot_name"] = "Warblade of the Hakkari (Main Hand)",["prio"] = "Prio: Hunter > MS->OS",},
{["loot_id"] = "19876",["loot_name"] = "Soul Corrupter's Necklace",["prio"] = "Prio: Warlock > MS->OS",},
{["loot_id"] = "20264",["loot_name"] = "Peacekeeper Gauntlets",["prio"] = "Prio: MS->OS",},
{["loot_id"] = "22739",["loot_name"] = "Tome of Polymorph: Turtle",["prio"] = "Prio: Mage",},
{["loot_id"] = "19947",["loot_name"] = "Nat Pagle's Broken Reel",["prio"] = "Prio: Warrior Tank = Druid Tank > MS->OS",},
{["loot_id"] = "19945",["loot_name"] = "Foror's Eyepatch",["prio"] = "Prio: Druid Tank MS->OS",},
}
